name: SSH to EC2 with SSH

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          
          wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org
          sudo systemctl start mongod
          systemctl status mongod
          npm install
      - name: Run Npm TEST
        run: |
          npm test
          
      - name: Install AWS CLI
        uses: actions/aws/cli@v2
        with:
          aws-version: 'lastest'
          
      - name: Send command to EC2 instance
        run: |
          aws ec2 send-command --instance-ids i-0aa025d31f6d2b69d --document-name "AWS-RunShellScript" --parameters commands="echo 'Hello, world!'" --output text
        env:
          AWS_REGION: ap-southeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  


        
          

        
