name: SSH to EC2 with SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: SSH to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          TEST_TEST: ${{ secrets.TEST_TEST }}
          HOST: 3.26.73.244
        run: |
          echo "$TEST_TEST" > mykey.pem
          cat mykey.pem
        
