name: List S3 objects
on:
  push:
    branches:
      - main

jobs:
  list-s3-objects:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: List objects in S3 bucket
      run: |
        aws s3 sync . s3://mysamplebucket309
        aws s3 sync s3://mysamplebucket309 /tmp/my-folder/
        aws ssm start-session --target i-0aa025d31f6d2b69d --document-name AWS-StartInteractiveCommand --parameters "commands=sudo rm -rf /home/ubuntu/chatgptTest/*,sudo mv /tmp/my-folder/* /home/ubuntu/chatgptTest/"
        ls -la
        

        
