name: List S3 objects
on:
  push:
    branches:
      - main

jobs:
  list-s3-objects:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: List objects in S3 bucket
      run: |
        aws s3 sync . s3://mysamplebucket309
        aws ssm send-command --document-name "AWS-RunShellScript" --parameters commands="sudo su ubuntu" --targets "Key=instanceids,Values=i-0aa025d31f6d2b69d"
        
        aws ssm send-command --document-name "AWS-RunShellScript" --parameters commands="aws s3 sync s3://mysamplebucket309 /home/ubuntu/chatgptTest" --targets "Key=instanceids,Values=i-0aa025d31f6d2b69d"


        
