name: Example Workflow

on: push

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          
      - name: Install AWS CLI
        run: |
          npm install -g aws-cli
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Use AWS CLI
        run: |
          aws --version
          aws ec2 send-command --instance-ids i-1234567890abcdef --document-name "AWS-RunShellScript" --parameters commands="echo 'Hello, world!'" --output text
