name: SSH to EC2 with SSH

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          
          wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org
          sudo systemctl start mongod
          systemctl status mongod
          npm install
      - name: Run Npm TEST
        run: |
          npm test
          
          
  


        
          

      - name: SSH to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_PATH: /home/ubuntu/chatgptTest
          HOST: 3.26.73.244
        run: |
          wget -qO- https://ipecho.net/plain ; echo
          eval "$(ssh-agent -s)"
          echo "$SSH_PRIVATE_KEY" | ssh-add -
          echo "$SSH_PRIVATE_KEY" > mykey.pem
          chmod 400 mykey.pem
          ls -la
          ssh -o StrictHostKeyChecking=no -t -t -i mykey.pem ubuntu@$HOST "ls"
          
          sudo rsync -r -v -e "ssh -i mykey.pem -o StrictHostKeyChecking=no" . ubuntu@$HOST:$REMOTE_PATH
        

        
