name: SSH to EC2 with SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: SSH to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          LOCAL_PATH: $GITHUB_WORKSPACE
          HOST: 3.26.73.244
        run: |
          eval "$(ssh-agent -s)"
          echo "$SSH_PRIVATE_KEY" | ssh-add -
          echo "$SSH_PRIVATE_KEY" > mykey.pem
          chmod 400 mykey.pem
          ls -la
          ssh -o StrictHostKeyChecking=no -t -t -i mykey.pem ubuntu@$HOST "ls"
          
          sudo rsync -r -e "ssh -i mykey.pem -o StrictHostKeyChecking=no" . ubuntu@$HOST:$REMOTE_PATH/
        

        
